### ISSUE TITLE
Variable and function coloring is off

### ISSUE THREAD

**Issue by mcanders** [IndicaInkwell/language-gdscript#1]
Variables and functions are yellow rather than white (using the default One Dark theme).  Additionally variable declarations show up in red.

Here is a gdscript snippet: 
![screenshot from 2015-12-09 21-49-10](https://cloud.githubusercontent.com/assets/2694663/11707945/e551ea30-9ebe-11e5-9a64-3204b3f082c1.png)

Compare that to this C# snippet:
![screenshot from 2015-12-09 21-49-32](https://cloud.githubusercontent.com/assets/2694663/11707938/ddd972fa-9ebe-11e5-8db3-b9d8ee6bb186.png)

The C# coloring follows the "standard" atom color scheme.

**Comment by IndicaInkwell** [comment]
Hi, thanks for posting an issue! The grammar is definitely in real need of a good refactoring and enhancement. I'll take a look at it tomorrow and see what I can do.

**Comment by IndicaInkwell** [comment]
How do these look to you?

Overview of Highlighting
![highlight-overview](https://cloud.githubusercontent.com/assets/12477404/11727659/043a9b1a-9f3a-11e5-858c-f8b1d3380850.png)

Highlighted Snippets
![highlight-snippets](https://cloud.githubusercontent.com/assets/12477404/11727660/045b94e6-9f3a-11e5-8463-8ee93cb79fea.png)

**Comment by mcanders** [comment]
Much better!  Thanks for the quick response!

**Comment by mcanders** [comment]
Actually I do have one critique.  With the new grammar, function declarations and function calls are both colored blue.  These are conceptually different things and they are generally not colored the same (function calls are usually the same color as variables.  white in this case).  Similarly, class declarations and class references are both colored yellow.  The class references should also probably be white.

**Comment by IndicaInkwell** [comment]
Yeah, I agree, the function calls should be white. For classes, it follows js and java, where constructors are highlighted as well. I personally prefer that. However, for static use and built-in non .new constructible types like Vector will be white. Does that sound alright?

**Comment by mcanders** [comment]
Yeah that sounds good.  Thanks again!

**Comment by IndicaInkwell** [comment]
Sweet, you're welcome and thanks for your input!
