### ISSUE TITLE
[Feature Request] "Go to function" functionality

### ISSUE THREAD

**Issue by kubecz3k** [IndicaInkwell/language-gdscript#4]
First of all I would like to thank you very much for this package. With each update it's more and more usable. Great work! Now lets go to the point :) 
I'm a noob atom user (usually trying once per couple weeks to see how much improvements is made in language-gdscript packpacge :)) Is there any way to have list with al the function in opened scripts? If I'm correct normally in Atom it's done via symbols (ctrl+r short-cut). 
As far as I see no symbols are generated currently by default.. was trying to use https://atom.io/packages/symbol-gen package with addition of simple regex to generate symbols for every function in the project... but in the end I was not able to generate them. 
Once more thanks a lot!

**Comment by IndicaInkwell** [comment]
Yo! Try using the [goto](https://atom.io/packages/goto) package for symbols based on the language grammar. It works okay as is, but it seems to grab all functions. That's an issue with the grammar, I'll look into it and see what should be changed.

**Comment by IndicaInkwell** [comment]
Okay, fixed the grammar thing with goto package and published to apm. It generates symbols like a charm :smiley:

**Comment by kubecz3k** [comment]
@IndicaInkwell Thanks a lot, It's working very nice! I think you should mention in package description that it supports goto package (it's always good to know what else we can install to have the best functionality - and also for Atom noobs like me that don't even know these packages exists) :)
