### ISSUE TITLE
Highlight keyword `signal`

### ISSUE THREAD

**Issue by Kazuo256** [IndicaInkwell/language-gdscript#5]
Issue #2 addressed a few new keywords, but this one came up more recently.

**Comment by IndicaInkwell** [comment]
Hi, thanks for posting an issue! I added the signal keyword and will be pushing it with other commits in a few minutes.

**Comment by IndicaInkwell** [comment]
Commits pushed!

**Comment by Kazuo256** [comment]
Nice, thanks a lot!
