### ISSUE TITLE
Add highlight to 'func' when preceded by static

### ISSUE THREAD

**Issue by OrenjiAkira** [IndicaInkwell/language-gdscript#6]
When preceded by the keyword 'static', the keyword 'func' is not highlighted. It'd be cool if it was.

**Comment by IndicaInkwell** [comment]
Hi, thanks for posting an issue. I'll have a look and see why it's not highlighting func now.

**Comment by IndicaInkwell** [comment]
Okay, I believe I got it working. Let me know if it's not working right.

**Comment by OrenjiAkira** [comment]
It is working alright. Thanks! That was fast too

**Comment by IndicaInkwell** [comment]
Cool! You're welcome, glad to help :)
